// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEBqt1fy7Esvb1cqgGe-1fCDGTdFitw64',
    appId: '1:1081059307303:web:1ec4442435aa1683e00302',
    messagingSenderId: '1081059307303',
    projectId: 'food-app-3d638',
    authDomain: 'food-app-3d638.firebaseapp.com',
    storageBucket: 'food-app-3d638.appspot.com',
    measurementId: 'G-ZR6NCB9HM8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8kRkLNwehXr4WXywCbq94nYVPBqM2Zwc',
    appId: '1:1081059307303:android:28052aa9fdf50e9de00302',
    messagingSenderId: '1081059307303',
    projectId: 'food-app-3d638',
    storageBucket: 'food-app-3d638.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7z54k4eGQaiK7v64UVJdHnd0pWU2Xzws',
    appId: '1:1081059307303:ios:db3b990aaf8226e7e00302',
    messagingSenderId: '1081059307303',
    projectId: 'food-app-3d638',
    storageBucket: 'food-app-3d638.appspot.com',
    androidClientId: '1081059307303-od33ep8q1hs5blv37otpsnicu3qshdga.apps.googleusercontent.com',
    iosClientId: '1081059307303-g3avbq84hbgcdvrps965h33gqjf0vpud.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodOrderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7z54k4eGQaiK7v64UVJdHnd0pWU2Xzws',
    appId: '1:1081059307303:ios:5bd591c59dc08677e00302',
    messagingSenderId: '1081059307303',
    projectId: 'food-app-3d638',
    storageBucket: 'food-app-3d638.appspot.com',
    androidClientId: '1081059307303-od33ep8q1hs5blv37otpsnicu3qshdga.apps.googleusercontent.com',
    iosClientId: '1081059307303-b6i628ddb7dvqmt79j8c49rgqbobku52.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodOrderApp.RunnerTests',
  );
}
